NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

## What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

## Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

### We will import NumPy library.

In [1]:
import numpy

In [2]:
# Example

arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### NumPy as np
NumPy is usually imported under the np alias.

In [3]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


### Checking NumPy Version
The version string is stored under __version__ attribute.

In [12]:
print(np.__version__)

1.23.5


# NumPy Creating Arrays

### Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D arra

In [14]:
import numpy as np
arr = np.array(42)
print(arr)

42


### 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.

Example
Create a 1-D array containing the values 1,2,3,4,5:

In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

#### Example
Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [17]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.

#### Example
Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

### Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

#### Example
Check how many dimensions the arrays have:

In [24]:
import numpy as np

a = np.array(2)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays

An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.

#### Example
Create an array with 5 dimensions and verify that it has 5 dimensions:

In [30]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print("Number of dimensions: ", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions:  5
