## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


## Negative Slicing

Use the minus operator to refer to an index from the end:

### Example
Slice from the index 3 from the end to index 1 from the end:

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


## STEP
Use the step value to determine the step of the slicing:

### Example
Return every other element from index 1 to index 5:

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr[1:13:2])

[ 2  4  6  8 10 12]


### Example
Return every other element from the entire array:

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
print(arr[::2])

[ 1  3  5  7  9 11 13]


## Slicing 2-D Arrays
### Example
From the second element, slice elements from index 1 to index 4 (not included):

In [16]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


### Example
From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [18]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
